manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/LOWPROKB
    - name: johnm
      url-base: https://github.com/johnm
  projects:
    - name: zmk
      remote: johnm
      revision: main
      import: app/west.yml
  self:
    path: config
